### ISSUE TITLE
Running task policy instead of distilled policy in select_action | distral1col.py

### ISSUE THREAD

**Issue by SapanaChaudhary** [Alfo5123/Robust-Multitask-RL#1]
https://github.com/Alfo5123/Robust-Multitask-RL/blob/1f23ad0b624e8d859b74fbe023e0c85564ed50e1/code/distral_1col0/distral1col.py#L67

Should it not be the following instead?
probs0 = distilled(Variable(state))

**Comment by Alfo5123** [comment]
@SapanaChaudhary 
In fact, you are correct, there is a bug. We indeed had some issues for the convergence of this method. Thanks for pointing it out.
