### ISSUE TITLE
A problem about Distral_2col

### ISSUE THREAD

**Issue by didizhu-judy** [Alfo5123/Robust-Multitask-RL#2]
May I ask if you did not actually implement the Distral_2col algorithm  in the paper "Distral: Robust Multitask Reinforcement Learning"?
The python code in the folder called distral_2col implements the same algorithm as distral_1col, which the optimization method just changed to alternate optimization.
Please point out if I say something wrong.Thank you!

**Comment by Alfo5123** [comment]
As far as I remember (I worked on this project a long time ago) the difference between the implementations was whether we use the screen or the coordinates as the state. Indeed we also tried experimenting with different optimizations schemes as well, so you are right.
